### ISSUE TITLE
End Rod Blue (First and Base for End Rods) Not working

### ISSUE THREAD

**Issue by Alovon12** [CactusHamster/EndRodModDebug#1]
Using End Rod.JSON from Minecraft's Default model folder, does not work, and the best that can be done is Log Rotation for the End rods, the rods still don't connect, and do not work with the assigned texture 

https://drive.google.com/file/d/1G8vfIC8jAdI7x24ZoKavvV_A8gjBHWNM/view?usp=sharing

**Comment by CactusHamster** [comment]
Working on the issue...
Almost done.

**Comment by CactusHamster** [comment]
Done! Rotating is fixed. However, there is an MCreator bug that keeps the bounding box from rotating with the model.
